// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5xu4vYOa7QJFbstzJS0bEj392cNA9vRk',
    appId: '1:99986217275:web:8a61c9dd80c7ef2ea8ff1e',
    messagingSenderId: '99986217275',
    projectId: 'ja-ar-cards',
    authDomain: 'ja-ar-cards.firebaseapp.com',
    storageBucket: 'ja-ar-cards.appspot.com',
    measurementId: 'G-TBF65ET622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg--_wvH8WUCAkn-RqJRdiu4Q-mZ76qck',
    appId: '1:99986217275:android:edc1977855147b20a8ff1e',
    messagingSenderId: '99986217275',
    projectId: 'ja-ar-cards',
    storageBucket: 'ja-ar-cards.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0VbxfjnWAq7pihD_q6gebZVJRq_aWG5s',
    appId: '1:99986217275:ios:152316fb46f504cda8ff1e',
    messagingSenderId: '99986217275',
    projectId: 'ja-ar-cards',
    storageBucket: 'ja-ar-cards.appspot.com',
    iosBundleId: 'com.ordYoung.japanesecards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0VbxfjnWAq7pihD_q6gebZVJRq_aWG5s',
    appId: '1:99986217275:ios:e869ea7ea574a3b0a8ff1e',
    messagingSenderId: '99986217275',
    projectId: 'ja-ar-cards',
    storageBucket: 'ja-ar-cards.appspot.com',
    iosBundleId: 'com.ordYoung.japanesecards.RunnerTests',
  );
}
